import { test, expect, type Page } from '@playwright/test'
import type { AppState } from '../../src/types'
import { documentAt, documentDraft, documentFamily } from '../documentFixtures'
import { saveInvoiceDraft } from '../../src/lib/invoiceActions'
import { parseBackup, serializeBackup, STORAGE_KEY } from '../../src/lib/storage'

async function seed(page: Page, state: AppState) {
  await page.goto('/')
  await page.evaluate(async (raw) => {
    const path = '/src/lib/storage.ts'
    const { StorageSession } = await import(path)
    await new StorageSession().restore(raw)
  }, serializeBackup(state))
  await page.reload()
}

async function stored(page: Page) {
  return parseBackup((await page.evaluate((key) => localStorage.getItem(key), STORAGE_KEY))!)
}

for (const width of [390, 1280]) {
  test(`P10: feste Listen und eindeutige Hauptaktionen bei ${width}px`, async ({ page }) => {
    await page.setViewportSize({ width, height: 900 })
    await page.clock.setFixedTime(new Date('2026-09-10T12:00:00Z'))
    const family = documentFamily()
    family.students[0].name = 'Zora'; family.students[1].name = 'Anna'
    family.guardians[0].name = 'Zora Familie'; family.guardians[1].name = 'Anna Familie'
    let state = saveInvoiceDraft(family, documentDraft(), true, documentAt)
    state = saveInvoiceDraft(state, { ...documentDraft(), invoiceDate: '2026-09-02' }, true, documentAt)
    await seed(page, state)
    await expect(page.getByRole('button', { name: 'Neue Rechnung', exact: true })).toHaveCount(1)
    await expect(page.getByRole('searchbox', { name: 'Rechnungen durchsuchen', exact: true })).toHaveCount(1)
    await expect(page.getByRole('button', { name: /sortieren/ })).toHaveCount(0)
    await expect(page.locator('tbody .invoice-detail-link')).toHaveText(['2026-0002-a', '2026-0001-a'])
    const search = page.getByRole('searchbox', { name: 'Rechnungen durchsuchen', exact: true })
    await search.fill('2026-0001-a')
    await expect(page.locator('tbody .invoice-detail-link')).toHaveText(['2026-0001-a'])
    await search.fill('')
    await page.getByRole('combobox', { name: 'Status', exact: true }).selectOption('paid')
    await expect(page.getByText('Nichts gefunden', { exact: true })).toBeVisible()
    await page.getByRole('combobox', { name: 'Status', exact: true }).selectOption('all')
    const navigation = width === 390 ? page.locator('.mobile-bottom-nav') : page.locator('.sidebar')
    await navigation.getByRole('button', { name: 'Personen', exact: true }).click()
    await expect(page.locator('.student-card h3')).toHaveText(['Anna', 'Zora'])
    await expect(page.getByRole('combobox', { name: 'Personenlisten sortieren' })).toHaveCount(0)
    await expect(page.getByRole('button', { name: 'Lernende Person anlegen', exact: true })).toHaveCount(1)
    await expect(page.getByRole('button', { name: 'Neue Rechnung', exact: true })).toHaveCount(0)
    await navigation.getByRole('button', { name: 'Einstellungen', exact: true }).click()
    await expect(page.getByRole('button', { name: 'JSON exportieren', exact: true })).toBeVisible()
    await navigation.getByRole('button', { name: 'Rechnungen', exact: true }).click()
    await expect(page.getByRole('button', { name: 'JSON exportieren', exact: true })).toHaveCount(0)
    await page.getByRole('button', { name: 'Neue Rechnung', exact: true }).press('Enter')
    await expect(page.getByRole('dialog', { name: 'Neue Rechnung', exact: true })).toBeVisible()
    await page.keyboard.press('Escape')
    await expect(page.getByRole('button', { name: 'Neue Rechnung', exact: true })).toBeFocused()
  })

  test(`P10: finale Kernaktionen, Details und Korrektur mit Fokus bei ${width}px`, async ({ page }, testInfo) => {
    await page.setViewportSize({ width, height: 900 })
    const state = saveInvoiceDraft(documentFamily(), documentDraft(), true, documentAt)
    const original = structuredClone(state.documentVersions[0])
    await seed(page, state)
    await page.getByRole('button', { name: 'Aktionen für 2026-0001-a öffnen', exact: true }).click()
    await expect(page.getByRole('menuitem', { name: 'Bearbeiten', exact: true })).toHaveCount(0)
    await page.keyboard.press('Escape')
    const opener = page.getByRole('button', { name: '2026-0001-a', exact: true })
    await opener.press('Enter')
    const detail = page.locator('.invoice-detail')
    await expect(detail.getByRole('button', { name: 'PDF / Drucken', exact: true })).toBeVisible()
    await expect(detail.getByRole('button', { name: 'Versendet / offen', exact: true })).toBeVisible()
    await expect(detail.getByRole('button', { name: /bearbeiten|speichern/i })).toHaveCount(0)
    await expect(detail.getByRole('heading', { name: 'Belegversionen', exact: true })).toBeHidden()
    const summary = detail.getByText('Details', { exact: true })
    await summary.press('Enter')
    await expect(detail.getByRole('heading', { name: 'Belegversionen', exact: true })).toBeVisible()
    await expect(detail.getByRole('heading', { name: 'Zahlungszuordnung', exact: true })).toBeVisible()
    await summary.press('Enter')
    const correction = detail.getByRole('button', { name: 'Korrigieren', exact: true })
    await correction.press('Enter')
    const dialog = page.getByRole('dialog', { name: 'Rechnung korrigieren', exact: true })
    await expect(dialog.getByRole('textbox', { name: 'Korrekturgrund', exact: true })).toBeFocused()
    await page.keyboard.press('Escape')
    await expect(correction).toBeFocused()
    await correction.press('Enter')
    await dialog.getByRole('textbox', { name: 'Korrekturgrund', exact: true }).fill('Preis berichtigen')
    await dialog.getByRole('button', { name: 'Korrekturentwurf erzeugen', exact: true }).click()
    await expect(page.getByRole('dialog', { name: 'Korrekturentwurf bearbeiten', exact: true })).toBeVisible()
    const after = await stored(page)
    expect(after.documentVersions[0]).toEqual(original)
    expect(after.invoices).toHaveLength(2)
    expect(after.invoices[1].number).toBeNull()
    expect(after.invoices[1].correction?.replacesId).toBe(original.id)
    await page.keyboard.press('Escape')
    await page.getByRole('button', { name: '2026-0001-a', exact: true }).click()
    await expect(detail.getByRole('button', { name: 'Korrekturentwurf öffnen', exact: true })).toBeVisible()
    await testInfo.attach(`p10-final-${width}.png`, { body: await page.screenshot(), contentType: 'image/png' })
    await page.keyboard.press('Escape')
    await expect(opener).toBeFocused()
  })
}

test('P10: erforderliche historische Klärung ist sichtbar und Details bleiben erreichbar', async ({ page }) => {
  const state = saveInvoiceDraft(documentFamily(), documentDraft(), true, documentAt)
  state.documentVersions[0].conflicts.push({ path: 'snapshot.iban', message: 'Historische Kontoabweichung', values: ['"Alt"', '"Neu"'] })
  await seed(page, state)
  await page.getByRole('button', { name: '2026-0001-a', exact: true }).click()
  const detail = page.locator('.invoice-detail')
  await expect(detail.getByRole('alert').filter({ hasText: 'Historische Abweichungen müssen' })).toBeVisible()
  await expect(detail.getByRole('textbox', { name: 'Ergebnis der Klärung', exact: true })).toBeVisible()
  await detail.getByText('Details', { exact: true }).press('Enter')
  await expect(detail.getByRole('alert').filter({ hasText: 'Historische Abweichungen müssen' })).toBeVisible()
  await detail.getByRole('button', { name: 'Korrigieren', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: 'Rechnung korrigieren', exact: true })
  await expect(dialog.getByRole('alert')).toContainText('Vor der Finalisierung')
  await expect(dialog.getByRole('button', { name: 'Korrekturentwurf erzeugen', exact: true })).toBeEnabled()
  await page.keyboard.press('Escape')
  await detail.getByText('Details', { exact: true }).press('Enter')
  await detail.getByRole('textbox', { name: 'Ergebnis der Klärung', exact: true }).fill('Gesichertes Original geprüft')
  await detail.getByRole('button', { name: 'Klärung dokumentieren', exact: true }).click()
  await expect(detail.getByRole('alert').filter({ hasText: 'Historische Abweichungen müssen' })).toHaveCount(0)
  expect((await stored(page)).documentVersions).toEqual(state.documentVersions)
})
