import test from 'node:test'
import assert from 'node:assert/strict'
import { emptyState } from '../src/lib/defaults'
import { invoiceProfileErrors, invoiceSetupErrors, SMALL_BUSINESS_TAX_NOTICE, taxDataForInvoice } from '../src/lib/invoiceProfile'
import { invoiceFinalizationErrors } from '../src/lib/utils'
import { saveInvoiceDraft } from '../src/lib/invoiceActions'
import type { Guardian, InvoiceDraft } from '../src/types'
const at = '2026-09-08T12:00:00.000Z'
const guardian = (overrides: Partial<Guardian> = {}): Guardian => ({ id: 'guardian-profile', name: 'Erika Beispiel', email: 'erika@example.de', phone: '', address: { street: 'Familienweg 2', postalCode: '12345', city: 'Teststadt' }, iban: '', paymentNote: '', createdAt: at, updatedAt: at, ...overrides })
function completeState() { const state = emptyState(); state.settings = { ...state.settings, issuer: { ...state.settings.issuer, name: 'Gitarrenstudio Beispiel', street: 'Studioallee 1', postalCode: '12345', city: 'Teststadt' }, accountHolder: 'Gitarrenstudio Beispiel', iban: 'DE89370400440532013000', invoiceProfile: 'small-business', taxIdentifier: { kind: 'tax-number', value: '12/345/67890' } }; state.guardians = [guardian()]; state.students = [{ id: 'student-profile', name: 'Kind Beispiel', billingCode: 'a', guardianIds: ['guardian-profile'], note: '', active: true, createdAt: at, updatedAt: at }]; return state }
const draft = (): InvoiceDraft => ({ invoiceDate: '2026-09-08', dueDate: '2026-09-22', period: 'September 2026', guardianIds: ['guardian-profile'], studentIds: ['student-profile'], recipientStrategy: 'joint', items: [{ id: 'item-profile', studentId: 'student-profile', serviceDate: '2026-09-01', lessonType: 'solo', description: 'Gitarrenunterricht', quantity: 1, unit: 'Std.', unitPrice: 30 }], introText: '', freeText: '', legalText: '' })
test('Kleinunternehmerprofil prüft Einrichtung und Empfänger feldgenau', () => { const state = completeState(); assert.deepEqual(invoiceSetupErrors(state.settings), []); assert.deepEqual(invoiceFinalizationErrors(state, draft()), []); const incomplete = { ...state.settings, issuer: { ...state.settings.issuer, street: '' }, taxIdentifier: { ...state.settings.taxIdentifier, value: '' } }; const setup = invoiceSetupErrors(incomplete).map((error) => error.message).join(' '); assert.match(setup, /Rechnungssteller: Straße & Hausnummer fehlt/); assert.match(setup, /Steuernummer: Steuerliche Identifikationsangabe fehlt/); const recipient = invoiceProfileErrors(state.settings, [guardian({ address: { street: '', postalCode: '', city: '' } })]).map((error) => error.message).join(' '); assert.match(recipient, /Familien → Erika Beispiel: Straße & Hausnummer fehlt/); assert.match(recipient, /PLZ fehlt/); assert.match(recipient, /Ort fehlt/) })
test('unvollständige Einrichtung erlaubt Entwurf, blockiert aber Finalisierung ohne Nummernverbrauch', () => { const state = completeState(); state.settings.taxIdentifier.value = ''; const saved = saveInvoiceDraft(state, draft(), false, at); assert.equal(saved.invoices[0].number, null); assert.deepEqual(saved.counters, {}); assert.throws(() => saveInvoiceDraft(state, draft(), true, at), /Steuernummer.*fehlt/); assert.deepEqual(state.invoices, []); assert.deepEqual(state.counters, {}) })
test('neuer Beleg friert Profil und verwendete Steuerkennung ein; heutige Änderungen wirken nicht zurück', () => { const state = completeState(); const issued = saveInvoiceDraft(state, draft(), true, at); const invoice = issued.invoices[0]; assert.equal(invoice.snapshot?.invoiceProfile, 'small-business'); assert.deepEqual(invoice.snapshot?.taxIdentifier, { kind: 'tax-number', value: '12/345/67890' }); issued.settings.taxIdentifier = { kind: 'vat-id', value: 'DE123456789' }; assert.deepEqual(taxDataForInvoice(invoice, issued.settings).taxIdentifier, { kind: 'tax-number', value: '12/345/67890' }); assert.equal(SMALL_BUSINESS_TAX_NOTICE, 'Steuerbefreiung für Kleinunternehmer (§ 19 UStG).') })
